version: '3.8'

services:
  # --- Databases ---
  postgres_auth:
    image: postgres:16-alpine
    container_name: falconpay-pg-auth
    environment:
      POSTGRES_USER: falconpay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  postgres_user:
    image: postgres:16-alpine
    container_name: falconpay-pg-user
    environment:
      POSTGRES_USER: falconpay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  postgres_payment:
    image: postgres:16-alpine
    container_name: falconpay-pg-payment
    environment:
      POSTGRES_USER: falconpay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"
    volumes:
      - pg_payment_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  postgres_wallet:
    image: postgres:16-alpine
    container_name: falconpay-pg-wallet
    environment:
      POSTGRES_USER: falconpay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    ports:
      - "5435:5432"
    volumes:
      - pg_wallet_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  postgres_reporting:
    image: postgres:16-alpine
    container_name: falconpay-pg-reporting
    environment:
      POSTGRES_USER: falconpay
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reporting_db
    ports:
      - "5436:5432"
    volumes:
      - pg_reporting_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  redis:
    image: redis:7-alpine
    container_name: falconpay-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - falconpay-network

  mongo:
    image: mongo:7
    container_name: falconpay-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - falconpay-network

  # --- Messaging Infrastructure ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: falconpay-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - falconpay-network

  kafka-ui:
    image: tchiotludo/akhq
    container_name: falconpay-kafka-ui
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka:
              properties:
                bootstrap.servers: "kafka:29092"
    networks:
      - falconpay-network

  postgres_keycloak:
    image: postgres:16-alpine
    container_name: falconpay-pg-keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5437:5432"
    volumes:
      - pg_keycloak_data:/var/lib/postgresql/data
    networks:
      - falconpay-network

  # --- Security Infrastructure ---
  vault:
    image: hashicorp/vault:1.15
    container_name: falconpay-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    networks:
      - falconpay-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: falconpay-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8888:8080"
    depends_on:
      - postgres_keycloak
    networks:
      - falconpay-network

  # --- Observability ---
  prometheus:
    image: prom/prometheus:latest
    container_name: falconpay-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - falconpay-network

  grafana:
    image: grafana/grafana:latest
    container_name: falconpay-grafana
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - falconpay-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: falconpay-jaeger
    networks:
      - falconpay-network

  loki:
    image: grafana/loki:latest
    container_name: falconpay-loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - falconpay-network

  promtail:
    image: grafana/promtail:latest
    container_name: falconpay-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - falconpay-network

  # --- DEVELOPMENT PROFILE (Hot Reload) ---
  api-gateway-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-gateway-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run start:dev -- api-gateway
    environment:
      - AUTH_SERVICE_URL=http://auth-service-dev:3001
      - USER_SERVICE_URL=http://user-service-dev:3002
      - PAYMENT_SERVICE_URL=http://payment-service-dev:3003
      - WALLET_SERVICE_URL=http://wallet-service-dev:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service-dev:3005
      - REPORTING_SERVICE_URL=http://reporting-service-dev:3006
    networks:
      - falconpay-network
    depends_on:
      - auth-service-dev

  auth-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-auth-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
      - "50051:50051" # gRPC
    command: npm run start:dev -- auth-service
    environment:
      - DB_HOST=postgres_auth
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_auth
      - kafka

  user-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-user-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3002"
    command: npm run start:dev -- user-service
    environment:
      - DB_HOST=postgres_user
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_user

  payment-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-payment-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3003:3003"
    command: npm run start:dev -- payment-service
    environment:
      - DB_HOST=postgres_payment
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=payment_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_payment

  wallet-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-wallet-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3004:3004"
    command: npm run start:dev -- wallet-service
    environment:
      - DB_HOST=postgres_wallet
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=wallet_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_wallet

  notification-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-notification-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3005:3005"
    command: npm run start:dev -- notification-service
    environment:
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network

  reporting-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-reporting-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3006:3006"
    command: npm run start:dev -- reporting-service
    environment:
      - DB_HOST=postgres_reporting
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=reporting_db
      - MONGO_URI=mongodb://mongo:27017/reporting
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_reporting
      - mongo

  reconciliation-service-dev:
    profiles: [ "dev" ]
    image: node:20-alpine
    container_name: falconpay-reconciliation-dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm run start:dev -- reconciliation-service
    environment:
      - DB_HOST_PAYMENT=postgres_payment
      - DB_HOST_WALLET=postgres_wallet
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
    networks:
      - falconpay-network
    depends_on:
      - postgres_payment
      - postgres_wallet

  frontend-dev:
    profiles: [ "dev" ]
    build:
      context: ./frontend
    container_name: falconpay-frontend-dev
    ports:
      - "80:80"
    networks:
      - falconpay-network
    depends_on:
      - api-gateway-dev

  # --- PRODUCTION PROFILE (Optimized) ---
  api-gateway:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    container_name: falconpay-api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3003
      - WALLET_SERVICE_URL=http://wallet-service:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
      - REPORTING_SERVICE_URL=http://reporting-service:3006
    networks:
      - falconpay-network
    depends_on:
      - auth-service

  auth-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: auth-service
    container_name: falconpay-auth-service
    environment:
      - DB_HOST=postgres_auth
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_auth
      - kafka

  user-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    container_name: falconpay-user-service
    environment:
      - DB_HOST=postgres_user
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=user_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_user

  payment-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: payment-service
    container_name: falconpay-payment-service
    environment:
      - DB_HOST=postgres_payment
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=payment_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_payment

  wallet-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: wallet-service
    container_name: falconpay-wallet-service
    environment:
      - DB_HOST=postgres_wallet
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=wallet_db
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_wallet

  notification-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: notification-service
    container_name: falconpay-notification-service
    environment:
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network

  reporting-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: reporting-service
    container_name: falconpay-reporting-service
    environment:
      - DB_HOST=postgres_reporting
      - DB_PORT=5432
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
      - DB_NAME=reporting_db
      - MONGO_URI=mongodb://mongo:27017/reporting
      - KAFKA_BROKERS=kafka:29092
    networks:
      - falconpay-network
    depends_on:
      - postgres_reporting
      - mongo

  reconciliation-service:
    profiles: [ "prod" ]
    build:
      context: .
      args:
        SERVICE_NAME: reconciliation-service
    container_name: falconpay-reconciliation-service
    environment:
      - DB_HOST_PAYMENT=postgres_payment
      - DB_HOST_WALLET=postgres_wallet
      - DB_USERNAME=falconpay
      - DB_PASSWORD=password
    networks:
      - falconpay-network
    depends_on:
      - postgres_payment
      - postgres_wallet

  frontend:
    profiles: [ "prod" ]
    build:
      context: ./frontend
    container_name: falconpay-frontend
    ports:
      - "80:80"
    networks:
      - falconpay-network
    depends_on:
      - api-gateway

networks:
  falconpay-network:
    driver: bridge

volumes:
  pg_auth_data:
  pg_user_data:
  pg_payment_data:
  pg_wallet_data:
  pg_reporting_data:
  pg_keycloak_data:
  redis_data:
  mongo_data:
